apt:

packages:
  - apt-transport-https
  - ca-certificates
  - curl
  - gnupg-agent
  - software-properties-common
  - nginx
  - php
  - php-mysql
  - libapache2-mod-php
  - php-gd
  - php-fpm
  - php-curl
  - zip
  - mysql-client
  - libmysqlclient-dev
  - mysql-server

package-update: true
package_upgrade: true
# Enable ipv4 forwarding, required on CIS hardened machines
write_files:
  - path: /etc/sysctl.d/enabled_ipv4_forwarding.conf
    content: |
      net.ipv4.conf.all.forwarding=1
  - path: /etc/cron.d/letsencrypt_renew 
    owner: root:root
    content: "15 3 * * * /usr/bin/certbot renew --quiet"
        
runcmd:
  - source /root/.env
  - apt-get update -y
  - snap install core; sudo snap refresh core
  - snap install --classic certbot
  - sudo apt-get -y install bacula-client
