apt:

packages:
  - apt-transport-https
  - ca-certificates
  - curl
  - gnupg-agent
  - software-properties-common
  - nginx
  - php
  - php-mysql
  - libapache2-mod-php
  - php-gd
  - php-fpm
  - php-curl
  - zip
  - mysql-client
  - libmysqlclient-dev
  - mysql-server

package-update: true
package_upgrade: true
# Enable ipv4 forwarding, required on CIS hardened machines
write_files:
  - path: /etc/sysctl.d/enabled_ipv4_forwarding.conf
    content: |
      net.ipv4.conf.all.forwarding=1
  - path: /etc/cron.d/letsencrypt_renew 
    owner: root:root
    content: "15 3 * * * /usr/bin/certbot renew --quiet"

  - path: /root/mysql.sh
    permissions: '0700'
    content: |
        mysql -e "CREATE DATABASE dev;"    
  #      mysql -e "CREATE USER 'dev'@'localhost' IDENTIFIED WITH mysql_native_password BY '${mysql_dev_Password}';"
  #      mysql -e "GRANT ALL PRIVILEGES ON dev.* TO 'dev'@'localhost';"
  #      mysql -e "CREATE USER 'stg'@'localhost' IDENTIFIED WITH mysql_native_password BY '${mysql_stg_Password}';"
  #      mysql -e "CREATE DATABASE stg;"
  #      mysql -e "GRANT ALL PRIVILEGES ON stg.* TO 'stg'@'localhost';"
  #      mysql -e "ALTER USER 'root'@'localhost' IDENTIFIED WITH mysql_native_password BY '${mysql_root_Password}';FLUSH PRIVILEGES;"
        
runcmd:
  - source /root/.env
  - apt-get update -y
  - snap install core; sudo snap refresh core
  - snap install --classic certbot
